name: CI

on: 
  schedule:
    - cron: '*/30 * * * *'
  
  push:
  release:
  
  
jobs:
  job_1:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    

    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: test.html
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
